In [20]:
# Dependencies and setup
import pandas as pd
import numpy as np
import requests
from pathlib import Path
import matplotlib.pyplot as plt

In [ ]:
# Import unemployment rate csv file, create DataFrame, and set index to Area Type
unemployment_data = Path('Resources/Local_Area_Unemployment_Statistics__LAUS___Annual_Average.csv')
unemployment_df = pd.read_csv(unemployment_data)
unemployment_df = unemployment_df.set_index('Area Type')
unemployment_df

In [22]:
# Filter Area Type to only include County and State data and reduce columns
area_type_df = unemployment_df.loc[['State','County'],
                                   ['Area Name', 'Year', 'Labor Force', 'Employment', 'Unemployment','Unemployment Rate']]
area_type_df

# Group by Year and calculate averages
year_grouped = area_type_df.groupby(['Year', 'Area Name']).mean()
year_grouped

# Reduce to only 2017-2022
recent = year_grouped.loc[[2017, 2018, 2019, 2020, 2021, 2022]]
recent

                       Labor Force  Employment  Unemployment  \
Year Area Name
2017 Alameda County       838200.0    807100.0       31100.0
     Alpine County           550.0       510.0          30.0
     Amador County         14690.0     13960.0         740.0
     Butte County         102000.0     96100.0        5900.0
     Calaveras County      21020.0     20010.0        1000.0
...                            ...         ...           ...
2022 Tulare County        207500.0    190500.0       16900.0
     Tuolumne County       19880.0     18990.0         890.0
     Ventura County       413600.0    398400.0       15200.0
     Yolo County          109000.0    104600.0        4400.0
     Yuba County           31600.0     29900.0        1700.0

                       Unemployment Rate
Year Area Name
2017 Alameda County                  3.7
     Alpine County                   6.2
     Amador County                   5.0
     Butte County                    5.8
     Calaveras County                4.8
...                                  ...
2022 Tulare County                   8.2
     Tuolumne County                 4.5
     Ventura County                  3.7
     Yolo County                     4.0
     Yuba County                     5.5

[354 rows x 4 columns]

,Area Name,Year,Labor Force,Employment,Unemployment,Unemployment Rate
Area Type,,,,,,
State,California,1990,15141700,14267900,873800,5.8
State,California,1991,15130500,13949700,1180800,7.8
State,California,1992,15303900,13871400,1432500,9.4
State,California,1993,15262300,13809100,1453200,9.5
State,California,1994,15266400,13943500,1322800,8.7
...,...,...,...,...,...,...
County,Tulare County,2022,207500,190500,16900,8.2
County,Tuolumne County,2022,19880,18990,890,4.5
County,Ventura County,2022,413600,398400,15200,3.7
County,Yolo County,2022,109000,104600,4400,4.0
County,Yuba County,2022,31600,29900,1700,5.5

In [42]:
weather_data = Path('20172022precipitation.csv')
weather_df = pd.read_csv(weather_data)
#weather_df.set_index('Name', inplace=True)
weather_df = weather_df.set_index('Name')
#weather_df = weather_df.loc
year_grouped = weather_df.groupby(['Year', 'Name'])
weather_df

,ID,State,Value,Rank,Anomaly (1901-2000 base period),1901-2000 Mean,Year
Name,,,,,,,
Alameda County,CA-001,California,24.97,110,6.22,18.75,2017
Alpine County,CA-003,California,64.24,127,28.10,36.14,2017
Amador County,CA-005,California,55.94,124,20.71,35.23,2017
Butte County,CA-007,California,56.41,107,12.00,44.41,2017
Calaveras County,CA-009,California,51.55,122,17.28,34.27,2017
...,...,...,...,...,...,...,...
Tulare County,CA-107,California,12.31,12,-9.53,21.84,2022
Tuolumne County,CA-109,California,29.48,24,-11.36,40.84,2022
Ventura County,CA-111,California,9.95,13,-10.46,20.41,2022
Yolo County,CA-113,California,11.49,12,-8.52,20.01,2022
Yuba County,CA-115,California,23.37,11,-14.36,37.73,2022

In [23]:
# Import age csv file and create DataFrame
age_data = Path('Resources/experiencing_homelessness_age_demographics.csv')
age_df = pd.read_csv(age_data)
age_df

,CALENDAR_YEAR,COC_ID,COC_NAME,AGE_GROUP_PUBLIC,EXPERIENCING_HOMELESSNESS_CNT
0,2017,All,California,18-24,15862
1,2017,All,California,25-34,28339
2,2017,All,California,35-44,25556
3,2017,All,California,45-54,27441
4,2017,All,California,55-64,23220
...,...,...,...,...,...
2136,2022,CA-614,San Luis Obispo County CoC,45-54,389
2137,2022,CA-614,San Luis Obispo County CoC,55-64,360
2138,2022,CA-614,San Luis Obispo County CoC,65+,174
2139,2022,CA-614,San Luis Obispo County CoC,Under 18,742
2140,2022,CA-614,San Luis Obispo County CoC,Unknown,62

In [24]:
# Create clean DataFrame by dropping rows with '*' in count column
clean_age_df = age_df.loc[age_df['EXPERIENCING_HOMELESSNESS_CNT']!='*']
clean_age_df

,CALENDAR_YEAR,COC_ID,COC_NAME,AGE_GROUP_PUBLIC,EXPERIENCING_HOMELESSNESS_CNT
0,2017,All,California,18-24,15862
1,2017,All,California,25-34,28339
2,2017,All,California,35-44,25556
3,2017,All,California,45-54,27441
4,2017,All,California,55-64,23220
...,...,...,...,...,...
2136,2022,CA-614,San Luis Obispo County CoC,45-54,389
2137,2022,CA-614,San Luis Obispo County CoC,55-64,360
2138,2022,CA-614,San Luis Obispo County CoC,65+,174
2139,2022,CA-614,San Luis Obispo County CoC,Under 18,742
2140,2022,CA-614,San Luis Obispo County CoC,Unknown,62

In [25]:
# Import ethnicity csv file and create DataFrame
ethnicity_data = Path('resources/experiencing_homelessness_ethnicity_demographics.csv')
ethnicity_df = pd.read_csv(ethnicity_data)
ethnicity_df

,CALENDAR_YEAR,COC_ID,COC_NAME,ETHNICITY,EXPERIENCING_HOMELESSNESS
0,2017,All,California,Hispanic/Latinx,59663
1,2017,All,California,Not Hispanic/Latinx,118412
2,2017,All,California,Unknown,3796
3,2017,CA-500,Santa Clara County CoC,Hispanic/Latinx,5010
4,2017,CA-500,Santa Clara County CoC,Not Hispanic/Latinx,5005
...,...,...,...,...,...
782,2022,CA-613,Imperial County CoC,Not Hispanic/Latinx,248
783,2022,CA-613,Imperial County CoC,Unknown,74
784,2022,CA-614,San Luis Obispo County CoC,Hispanic/Latinx,994
785,2022,CA-614,San Luis Obispo County CoC,Not Hispanic/Latinx,1722
786,2022,CA-614,San Luis Obispo County CoC,Unknown,144

In [26]:
# Import gender csv file and create DataFrame
gender_data = Path('resources/experiencing_homelessness_gender_demographics.csv')
gender_df = pd.read_csv(gender_data)
gender_df

,CALENDAR_YEAR,COC_ID,COC_NAME,GENDER,EXPERIENCING_HOMELESSNESS_CNT
0,2017,All,California,Female,78453
1,2017,All,California,Male,101150
2,2017,All,California,Non-Singular Gender,137
3,2017,All,California,Questioning Gender,*
4,2017,All,California,Transgender,667
...,...,...,...,...,...
1229,2022,CA-614,San Luis Obispo County CoC,Female,1279
1230,2022,CA-614,San Luis Obispo County CoC,Male,1556
1231,2022,CA-614,San Luis Obispo County CoC,Non-Singular Gender,*
1232,2022,CA-614,San Luis Obispo County CoC,Transgender,*
1233,2022,CA-614,San Luis Obispo County CoC,Unknown,14

In [27]:
# Import race csv file and create DataFrame
race_data = Path('resources/experiencing_homelessness_race_demographics.csv')
race_df = pd.read_csv(race_data)
race_df

,CALENDAR_YEAR,COC_ID,COC_NAME,RACE,EXPERIENCING_HOMELESSNESS
0,2017,All,California,"American Indian, Alaska Native, or Indigenous",5588
1,2017,All,California,Asian or Asian American,2951
2,2017,All,California,"Black, African American, or African",57413
3,2017,All,California,Multiple Races,8919
4,2017,All,California,Native Hawaiian or Pacific Islander,2547
...,...,...,...,...,...
1840,2022,CA-614,San Luis Obispo County CoC,"Black, African American, or African",144
1841,2022,CA-614,San Luis Obispo County CoC,Multiple Races,170
1842,2022,CA-614,San Luis Obispo County CoC,Native Hawaiian or Pacific Islander,27
1843,2022,CA-614,San Luis Obispo County CoC,Unknown,166
1844,2022,CA-614,San Luis Obispo County CoC,White,2244